homegateway:
  hardware: false
  mqtt:
    server:
      url: "tcp://localhost:1883"
    client:
      username: "hupan-raspberry"
      password: "password"
  switch:
    url: "http://localhost"

server:
  port: 8090
