
homegateway:
  hardware:
    debug-mode: true
  mqtt:
    server:
      url: "tcp://host:1883"
    client:
      username: "hupan-raspberry"
      password: "password"
  switch:
    url: "http://host"

server:
  port: 8090
